"""Config file generation — .env and YAML local overrides."""

from __future__ import annotations

import stat
from datetime import datetime
from pathlib import Path


def write_env_file(credentials: dict[str, str], auto_generated: dict[str, str]) -> None:
    """Write the .env file with all configuration."""
    all_vars = {**auto_generated, **credentials}

    lines = [
        "# ============================================================",
        "# TSAR CONFIGURATION — Auto-generated by setup wizard",
        f"# Generated: {datetime.now().isoformat()}",
        "# DO NOT COMMIT THIS FILE",
        "# ============================================================",
        "",
        "# ── EXCHANGE ───────────────────────────────────────────────",
        f"EXCHANGE_API_KEY={all_vars.get('EXCHANGE_API_KEY', '')}",
        f"EXCHANGE_SECRET={all_vars.get('EXCHANGE_SECRET', '')}",
        f"EXCHANGE_SANDBOX={all_vars.get('EXCHANGE_SANDBOX', 'true')}",
        "",
        "# ── NVIDIA AI ──────────────────────────────────────────────",
        f"NVIDIA_API_KEY={all_vars.get('NVIDIA_API_KEY', '')}",
        "",
        "# ── TELEGRAM ───────────────────────────────────────────────",
        f"TELEGRAM_BOT_TOKEN={all_vars.get('TELEGRAM_BOT_TOKEN', '')}",
        f"TELEGRAM_CHAT_ID={all_vars.get('TELEGRAM_CHAT_ID', '')}",
        "",
        "# ── TSAR API ──────────────────────────────────────────────",
        f"TSAR_API_KEY={all_vars.get('TSAR_API_KEY', '')}",
        f"TSAR_API_PORT={all_vars.get('TSAR_API_PORT', '8000')}",
        f"TSAR_TRADING_MODE={all_vars.get('TSAR_TRADING_MODE', 'paper')}",
        "",
        "# ── CORS ──────────────────────────────────────────────────",
        f"TSAR_CORS_ORIGINS={all_vars.get('TSAR_CORS_ORIGINS', 'http://localhost:3000')}",
        "",
        "# ── REDIS ─────────────────────────────────────────────────",
        "REDIS_HOST=redis",
        "REDIS_PORT=6379",
        f"REDIS_PASSWORD={all_vars.get('REDIS_PASSWORD', '')}",
        "",
    ]

    env_path = Path(".env")
    env_path.write_text("\n".join(lines))
    env_path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 600


def write_local_yaml_config(trading_mode: str = "paper") -> None:
    """Write config/local.yaml for environment-specific overrides."""
    config_dir = Path("config")
    config_dir.mkdir(exist_ok=True)

    content = f"""# ============================================================
# TSAR — Local Configuration Overrides
# Auto-generated by setup wizard. Gitignored.
# Takes precedence over default.yaml.
# ============================================================

app:
  trading_mode: "{trading_mode}"
  environment: "development"

exchanges:
  sandbox: true
  symbols:
    - "BTC/USDT"

risk:
  max_open_positions: 3
  max_single_position_pct: 0.10
  daily_loss_kill: -0.02

api:
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
"""
    local_path = config_dir / "local.yaml"
    local_path.write_text(content)


def setup_gitignore() -> list[str]:
    """Ensure sensitive files are gitignored. Returns list of entries added."""
    gitignore = Path(".gitignore")
    required_entries = [
        ".env",
        ".secrets.key",
        ".env.secrets",
        "config/local.yaml",
        "data/",
        "logs/",
    ]

    existing = gitignore.read_text() if gitignore.exists() else ""
    additions = [e for e in required_entries if e not in existing]

    if additions:
        with open(gitignore, "a") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write("\n# TSAR secrets & data (auto-added by setup)\n")
            for entry in additions:
                f.write(entry + "\n")

    return additions
